# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0

def pod_modules

  # Network
  pod 'SwiftyJSON'
  # Others
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'SnapKit'
  pod 'SDWebImage'
  pod 'SwiftyUserDefaults'
  pod 'IQKeyboardManagerSwift'
  pod 'CropViewController'
  # Google & Firebase
  pod 'GoogleSignIn'
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Messaging'
  pod 'Firebase/Analytics'
  pod 'Firebase/RemoteConfig'
  pod 'Firebase/DynamicLinks'
  pod 'MBProgressHUD', '~> 1.2.0'
  pod 'Moya', '~> 13.0.1'
end

target 'MeetTogether' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MeetTogether
  pod_modules
 
  target 'MeetTogetherTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MeetTogetherUITests' do
    # Pods for testing
  end
end
